# Generated by Django 6.0 on 2025-12-27 03:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_path",
                    models.CharField(
                        help_text="タスク関数のモジュールパス", max_length=512
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(
                        default="default", help_text="キュー名", max_length=255
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="優先度（-100〜100）"),
                ),
                (
                    "args_json",
                    models.JSONField(default=list, help_text="引数（JSON形式）"),
                ),
                (
                    "kwargs_json",
                    models.JSONField(
                        default=dict, help_text="キーワード引数（JSON形式）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        default="READY",
                        help_text="タスク状態",
                        max_length=20,
                    ),
                ),
                (
                    "run_after",
                    models.DateTimeField(
                        blank=True, help_text="実行開始可能時刻", null=True
                    ),
                ),
                ("enqueued_at", models.DateTimeField(help_text="キューイング時刻")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="実行開始時刻", null=True
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, help_text="実行終了時刻", null=True
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True, help_text="最後に試行した時刻", null=True
                    ),
                ),
                (
                    "return_value_json",
                    models.JSONField(
                        blank=True, help_text="戻り値（JSON形式）", null=True
                    ),
                ),
                (
                    "errors_json",
                    models.JSONField(default=list, help_text="エラー情報（JSON形式）"),
                ),
                (
                    "worker_ids_json",
                    models.JSONField(
                        default=list, help_text="ワーカーID一覧（JSON形式）"
                    ),
                ),
                (
                    "backend_name",
                    models.CharField(help_text="バックエンド名", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="レコード作成時刻"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="レコード更新時刻"),
                ),
            ],
            options={
                "verbose_name": "Database Task",
                "verbose_name_plural": "Database Tasks",
                "db_table": "django_database_task",
                "ordering": ["-priority", "enqueued_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after", "priority"],
                        name="ddt_status_run_priority_idx",
                    ),
                    models.Index(fields=["queue_name"], name="ddt_queue_name_idx"),
                    models.Index(fields=["status"], name="ddt_status_idx"),
                    models.Index(fields=["created_at"], name="ddt_created_at_idx"),
                ],
            },
        ),
    ]
