# Generated by Django 6.0 on 2025-12-27 06:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_path",
                    models.CharField(
                        help_text="Module path of the task function",
                        max_length=512,
                        verbose_name="task path",
                    ),
                ),
                (
                    "queue_name",
                    models.CharField(
                        default="default",
                        help_text="Queue name",
                        max_length=255,
                        verbose_name="queue name",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority (-100 to 100)",
                        verbose_name="priority",
                    ),
                ),
                (
                    "args_json",
                    models.JSONField(
                        default=list,
                        help_text="Arguments (JSON format)",
                        verbose_name="arguments",
                    ),
                ),
                (
                    "kwargs_json",
                    models.JSONField(
                        default=dict,
                        help_text="Keyword arguments (JSON format)",
                        verbose_name="keyword arguments",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SUCCESSFUL", "Successful"),
                        ],
                        default="READY",
                        help_text="Task status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "run_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest execution time",
                        null=True,
                        verbose_name="run after",
                    ),
                ),
                (
                    "enqueued_at",
                    models.DateTimeField(
                        help_text="Time when task was enqueued",
                        verbose_name="enqueued at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Execution start time",
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Execution end time",
                        null=True,
                        verbose_name="finished at",
                    ),
                ),
                (
                    "last_attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last attempt time",
                        null=True,
                        verbose_name="last attempted at",
                    ),
                ),
                (
                    "return_value_json",
                    models.JSONField(
                        blank=True,
                        help_text="Return value (JSON format)",
                        null=True,
                        verbose_name="return value",
                    ),
                ),
                (
                    "errors_json",
                    models.JSONField(
                        default=list,
                        help_text="Error information (JSON format)",
                        verbose_name="errors",
                    ),
                ),
                (
                    "worker_ids_json",
                    models.JSONField(
                        default=list,
                        help_text="List of worker IDs (JSON format)",
                        verbose_name="worker IDs",
                    ),
                ),
                (
                    "backend_name",
                    models.CharField(
                        help_text="Backend name",
                        max_length=255,
                        verbose_name="backend name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Record creation time",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Record update time",
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "database task",
                "verbose_name_plural": "database tasks",
                "ordering": ["-priority", "enqueued_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after", "priority"],
                        name="ddt_status_run_priority_idx",
                    ),
                    models.Index(fields=["queue_name"], name="ddt_queue_name_idx"),
                    models.Index(fields=["status"], name="ddt_status_idx"),
                    models.Index(fields=["created_at"], name="ddt_created_at_idx"),
                ],
            },
        ),
    ]
